### ISSUE TITLE
[Caption] Automatically generated captions

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#22]
We have a whole page on automatically generated captions, I think we should have a quick link in the sidebar and not repeat things from the page here.

**Comment by gfreedncam** [comment]
this is fine with me, but i don't know how to add a link to the sidebar.  would you be able to do this?

**Comment by yatil** [comment]
Thanks, @gfreedncam, Just let me know when you have made the changes and I am happy to add the sidebar link.

**Comment by gfreedncam** [comment]
deleted the brief section about auto-captions.  if you will add the sidebar link to the auto-captions page, i think that will close this issue.  tx.

**Comment by brewerj** [comment]
I noticed that this issue hadn't been closed, and looked back over the "production" page https://w3c.github.io/wai-tutorials/accessible-media/production-captions/ as well as the "automatic captions" page https://w3c.github.io/wai-tutorials/accessible-media/automatically-generated-captions/ . 

The most frequent questions (by far) that I get about captions are (1) whether to use automated captions, and (2) questions about how to use them, from people already assuming that that is what they should be using, because of how much they've heard about automatic captions.

I therefore think that Geoff's original cautionary point is worth keeping on the "production" page, along with a pointer over to the page specifically about automatic captions, so that it doesn't get missed, as it might in a sidebar. To avoid redundancy, perhaps the section on the "production" page could be removed, but a sentence could be added under "Resources for Quality Captions" stating & linking "Note caution about using automatic captions."

**Comment by yatil** [comment]
This hasn’t been closed because I did not have the final version to add the sidebar link. Happy to do that and then close.

**Comment by brewerj** [comment]
Actually, thanks for not adding a sidebar. Please see my last paragraph above, where I argue against using that approach, and instead suggested a different approach, which would be a cautionary note in the text flow of Resources for Quality Captions. In discussion today, Geoff seemed to support doing so.

**Comment by yatil** [comment]
I think a sidebar box would’ve been more visible than a paragraph at the end of the page, but I’ll happily make the change.
