### ISSUE TITLE
[audio description] SMIL3

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-intro#39]
> The only markup-based method for providing extended audio descriptions is to use [SMIL 3.0](https://www.w3.org/TR/SMIL3/), a language for writing interactive multimedia presentations. Support for SMIL is very limited, however, and may require the use of a custom player.

Can we do something so that the reader is not forced to do the research themselves? What means limited support? Does it work in browsers? How would I integrate this into my website? Is there a polyfill? Is this the best way to implement extended descriptions?

**Comment by gfreedncam** [comment]
i edited to include a bit of clarifying info.  as far as i know, there is one player that supports SMIL natively: the ambulant player (http://www.ambulantplayer.org/).  i'm not sure if it's even being supported any more, though.  old versions of quicktime used to support SMIL, but i'm pretty sure that support has vanished in current QT versions. i think we should mention SMIL in this tutorial is because authors CAN build it into custom players if they want, and it DOES actually provide a mechanism for conveying extended descriptions.    but i also think it's beyond the scope of the tutorial to go much further than that.
